name: message_in_a_botlle
description: "Welcome to an anonymous world"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.1
  image_picker: ^1.1.2
  riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  google_fonts: ^6.2.1
  http: ^1.2.2
  zego_uikit_prebuilt_call: ^4.16.14
  zego_uikit_signaling_plugin: ^2.8.7
  zego_zimkit: ^1.18.13
  zego_uikit_beauty_plugin: ^1.7.5
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
